# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: en

# avatar image url
head_img: ./images/avatar.png

profile_picture: ./images/profile_picture.jpg

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: 
  - "background-image:url('images/background/mononoke.jpg')"

home_background_mobile: 
  - "background-image:url('images/background/mononoke.jpg')"
  - "background-image:url('images/background/cuteboy.jpg')"
  - "background-image:url('images/background/protrait-1.jpg')"
  - "background-image:url('images/background/protrait-2.jpg')"
  - "background-image:url('images/background/protrait-3.jpg')"
  - "background-image:url('images/background/protrait-4.jpg')"

# Particle theme icon is adopts the ant design vue icons
# Linkï¼šhttps://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  home:
    icon:
      name: home
      theme: filled
    src: /
  about:
    icon:
      name: idcard
      theme: filled
    src: /about # å½“ä½ çš„åšå®¢rootä¸º '/' æ—¶
  archives:
    icon:
      name: folder
      theme: filled
    src: /archives
  friends:
    icon:
      name: heart
      theme: filled
    src: /friends
  categories:
    icon:
      name: book
      theme: filled
    src: /categories/Life # å½“ä½ çš„åšå®¢rootä¸ä¸º '/'ï¼Œè€Œæ˜¯å…¶å®ƒæ—¶ï¼Œä¾‹å¦‚ '/like/'
  tags:
    icon:
      name: tags
      theme: filled
    src: /tags/English

# side info card
card:
  enable: true
  description: ["A Malaysian high school student, currently 17 years old.", "I will share my thoughts and daily life here."]
  icon_links:
    discord:
      icon:
        type: img
        src: ./images/icon/discord.svg
      link: 'https://discord.com/users/709009923572498463'
    github:
      icon:
        type: img
        src: ./images/icon/github.png
      link: 'https://github.com/yuzhoumy'
    instagram:
      icon:
        type: img
        src: ./images/icon/instagram.svg
      link: 'https://www.instagram.com/yuzhou____/'
    telegram:
      icon:
        type: img
        src: ./images/icon/telegram.svg
      link: 'https://t.me/yamyeezhe'
    mail:
      icon:
        type: img
        src: ./images/icon/mail.svg
      link: 'mailto:1@yuzhou.my'
  friend_links:
    "More about me": /about

# footer info
footer:
  since: 2026
  # Customize the server domain name ICP
  ICP:
    enable: false
    code: 

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  clientID: 'Ov23liE3qUuVcTkWUTlO' # GitHub Application Client ID
  clientSecret: '73d13331643f00f83df432641af6a3d3e068b07e' # GitHub Application Client Secret
  repo: blog-comments # The name of repository of store comments
  owner: yuzhoumy # GitHub repo owner
  admin: ['yuzhoumy'] # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: en # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: full
